#!/usr/bin/env python3
"""Bake DejaVu Sans 2.37 into the renderer; no font library is needed on the HU.

python3 tools/generate_route_font.py /path/to/DejaVuSans.ttf
Install tools/route-font-requirements.txt first. Retain the font's license.
"""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("font")
args = parser.parse_args()
font = ImageFont.truetype(args.font, 16)
points = list(range(32, 127)) + list(range(160, 592)) + list(range(880, 1328))
points += list(range(8208, 8251))
missing = bytes(font.getmask("\uffff"))
glyphs = []
x = y = row_height = 0
width = 1024
for cp in sorted(set(points)):
    char = chr(cp)
    if bytes(font.getmask(char)) == missing:
        continue
    left, top, right, bottom = font.getbbox(char, anchor="ls")
    w, h = right - left, bottom - top
    if x + w + 2 > width:
        x = 0
        y += row_height + 2
        row_height = 0
    glyphs.append((cp, x + 1, y + 1, w, h, left, top + 15, round(font.getlength(char) * 64)))
    x += w + 2
    row_height = max(row_height, h)
height = 1
while height < y + row_height + 2:
    height *= 2
atlas = Image.new("L", (width, height))
draw = ImageDraw.Draw(atlas)
for cp, x, y, w, h, left, top, advance in glyphs:
    draw.text((x - left, y - top + 15), chr(cp), font=font, fill=255, anchor="ls")
raw = atlas.tobytes()
rle = []
pos = 0
while pos < len(raw):
    end = pos + 1
    while end < len(raw) and raw[end] == raw[pos] and end - pos < 255:
        end += 1
    rle += [end - pos, raw[pos]]
    pos = end
out = Path(__file__).resolve().parents[1] / "maneuver_render" / "route_font_data.h"
with out.open("w", encoding="ascii", newline="\n") as f:
    f.write("/* Generated by tools/generate_route_font.py; see LICENSE.DEJAVU. */\n")
    f.write(f"#define ROUTE_FONT_WIDTH {width}\n#define ROUTE_FONT_HEIGHT {height}\n")
    f.write("typedef struct { unsigned short cp,x,y,w,h; short left,top,advance; } route_glyph_t;\n")
    f.write("static const route_glyph_t route_glyphs[] = {\n")
    for glyph in glyphs:
        f.write("    {" + ",".join(map(str, glyph)) + "},\n")
    f.write("};\nstatic const unsigned char route_font_rle[] = {\n")
    for i in range(0, len(rle), 32):
        f.write("    " + ",".join(map(str, rle[i:i+32])) + ",\n")
    f.write("};\n")
print(f"{len(glyphs)} glyphs, {width}x{height}, {len(rle)} compressed bytes: {out}")
